name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Install Maven 3.9.6
    - name: Install Maven 3.9.6
      run: |
        wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
        tar -xvzf apache-maven-3.9.6-bin.tar.gz
        sudo mv apache-maven-3.9.6 /opt/maven
        sudo ln -sf /opt/maven/bin/mvn /usr/bin/mvn
 
    # List files for debugging
    - name: List files
      run: ls -R

    # Step 4: Verify Maven Version
    - name: Check Maven Version
      run: mvn -version

    # Step 5: Build with Maven
    - name: Build with Maven
      run: |
        cd HelloWorldApp
        mvn clean install
        

    # Step 6: Build Docker image
    - name: Build Docker Image
      run: |
        cd HelloWorldApp 
        docker build -t mahaar57/hello-world-app:${{ github.sha }} .

    # Step 7: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    # Step 8: Push Docker image
    - name: Push Docker Image
      run: docker push mahaar57/hello-world-app:${{ github.sha }}
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 1: SSH into the remote server
    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_PRIVATE_KEY }}
        script: |
          docker pull --platform linux/amd64 mahaar57/hello-world-app:${{ github.sha }}
          docker stop hello-world-app || true
          docker rm hello-world-app || true
          docker run --platform linux/amd64 -d -p 8080:8080 --name hello-world-app mahaar57/hello-world-app:${{ github.sha }}
